### ISSUE TITLE
ValueError: Non-consecutive added token '<mask>' found. Should have index 63996 but has index 64000 in saved vocabulary

### ISSUE THREAD

**Issue by amitkayal** [pysentimiento/pysentimiento#11]
I am getting following error while importing tokenizer. Is this allowed one?

**Code:**
`
tokenizer = BertTokenizer.from_pretrained('finiteautomata/bertweet-base-sentiment-analysis')
model = BertForSequenceClassification.from_pretrained('finiteautomata/bertweet-base-sentiment-analysis')
`
**Error**:
`
The tokenizer class you load from this checkpoint is not the same type as the class this function is called from. It may result in unexpected tokenization. 
The tokenizer class you load from this checkpoint is 'BertweetTokenizer'. 
The class this function is called from is 'BertTokenizer'.
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-8-069f22027c08> in <module>()
      2 
      3 # initialize the tokenizer for BERT models
----> 4 tokenizer = BertTokenizer.from_pretrained('finiteautomata/bertweet-base-sentiment-analysis')
      5 # initialize the model for sequence classification
      6 model = BertForSequenceClassification.from_pretrained('finiteautomata/bertweet-base-sentiment-analysis')

1 frames
/usr/local/lib/python3.7/dist-packages/transformers/tokenization_utils_base.py in _from_pretrained(cls, resolved_vocab_files, pretrained_model_name_or_path, init_configuration, use_auth_token, *init_inputs, **kwargs)
   1920                     # current length of the tokenizer.
   1921                     raise ValueError(
-> 1922                         f"Non-consecutive added token '{token}' found. "
   1923                         f"Should have index {len(tokenizer)} but has index {index} in saved vocabulary."
   1924                     )

ValueError: Non-consecutive added token '<mask>' found. Should have index 63996 but has index 64000 in saved vocabulary.
`

**Comment by finiteautomata** [comment]
Might be related to #8

**Comment by finiteautomata** [comment]
You should use `AutoTokenizer` and `AutoModelForSequenceClassification` instead of `BertTokenizer` and `BertModelForSequenceClassification`
