### ISSUE TITLE
How does this model compare to models trained on the Huggingface Emotion dataset?

### ISSUE THREAD

**Issue by mallorbc** [pysentimiento/pysentimiento#14]
These models and dataset are special in my mind due to the "other" tag which acts as a neutral tag.  Other models are trained on similar tasks like the one here https://huggingface.co/bhadresh-savani/distilbert-base-uncased-emotion

The dataset it is trained on is the Huggingface Emotion dataset.  The dataset has the same tags except the neutral tag.  That models claims to have an f1 score of 93.79, very good. 

This work claims to have an f1 score of 0.4756, not as good but these are different datasets.

How would this model perform on the Huggingface Emotion dataset?  If one does not care about the neutral tag, would they be better off using a model like the one I linked?  If so, could one use this model as a neutral emotion detector, and then default to the other model when neutral is not detected?

**Comment by finiteautomata** [comment]
Closing this. Feel free to reopen if you have any question
