### ISSUE TITLE
Return Output

### ISSUE THREAD

**Issue by Adrimta** [pysentimiento/pysentimiento#17]
Hi, 

I would like to return the output of analyzer. 

Eg. I would like to know, how many tweets are NEG or POS? 

How can I count the number of POS tweets?? 

Thank you.

**Comment by finiteautomata** [comment]
Hi @Adrimta. Your question looks more like a python question than something about `pysentimiento`. Please use StackOverflow for this.

This snippet might help you

```python
from pysentimiento import SentimentAnalyzer

analyzer = SentimentAnalyzer(lang="en")
# Repeat ten times this
sentences = ["This is great!", "This is something", "This is awful"]* 10

predictions = analyzer.predict(sentences)
Counter([pred.output for pred in ret])
# Returns Counter({'POS': 10, 'NEU': 10, 'NEG': 10})
```
