### ISSUE TITLE
[BUG] "No objects to concatenate") ValueError: No objects to concatenate

### ISSUE THREAD

**Issue by iaSalazar** [pysentimiento/pysentimiento#19]
**Describe the bug**
I am trying to train a model wiht my data using "python bin/train_sentiment.py "dccuchile/bert-base-spanish-wwm-cased" models/beto-sentiment-analysis/ --epochs 5 --lang es" i have the data in the proper folder but even if I remove the data I get the same error.

**To Reproduce**
pull repository
download tass data to proper folder
use python bin/train_sentiment.py "dccuchile/bert-base-spanish-wwm-cased" models/beto-sentiment-analysis/ --epochs 5 --lang es

Please provide a working code of your error and the stack trace or output related to it. 

The scrypt is looking for this folder /home/ivs/anaconda3/envs/ABD/lib/python3.7/site-packages/data/tass2020 and I have the data there (dev, test1.1/labels and train)

I am using the code from the repository with no changes.

**Expected behavior**
Trained model with my data.

**Environment**
aiohttp==3.8.1
aiosignal==1.2.0
async-timeout==4.0.1
asynctest==0.13.0
attrs==21.2.0
certifi==2021.10.8
charset-normalizer==2.0.7
click==8.0.3
click-plugins==1.1.1
cligj==0.7.2
datasets==1.15.1
dill==0.3.4
emoji==1.6.1
filelock==3.4.0
Fiona==1.8.20
fire==0.4.0
frozenlist==1.2.0
fsspec==2021.11.0
geopandas==0.9.0
huggingface-hub==0.1.2
idna==3.3
importlib-metadata==4.8.1
joblib==1.1.0
multidict==5.2.0
multiprocess==0.70.12.2
munch==2.5.0
numpy==1.21.2
packaging==21.3
pandas==1.3.4
py4j==0.10.7
pyarrow==6.0.1
pyparsing==3.0.6
pyproj==3.2.1
pysentimiento==0.2.5
pyspark==2.3.2
python-dateutil==2.8.2
pytz==2021.3
PyYAML==6.0
regex==2021.11.10
requests==2.26.0
Rtree==0.9.7
sacremoses==0.0.46
scikit-learn==1.0.1
scipy==1.7.2
Shapely==1.7.1
six==1.16.0
sklearn==0.0
spark-nlp==3.3.2
termcolor==1.1.0
threadpoolctl==3.0.0
tokenizers==0.10.3
torch==1.10.0
tqdm==4.62.3
transformers==4.12.5
typing-extensions==3.10.0.2
urllib3==1.26.7
xxhash==2.0.2
yarl==1.7.2
zipp==3.6.0

Full log:
`python bin/train_sentiment.py "distilbert-base-multilingual-cased" models/distilbert-es-sentiment-analysis/ --epochs 5 --lang es
================================================================================
 ================================================================================

Training distilbert-base-multilingual-cased in language es 

Loading dataset
Traceback (most recent call last):
  File "bin/train_sentiment.py", line 97, in <module>
    fire.Fire(train)
  File "/home/ivs/anaconda3/envs/ABD/lib/python3.7/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/home/ivs/anaconda3/envs/ABD/lib/python3.7/site-packages/fire/core.py", line 471, in _Fire
    target=component.__name__)
  File "/home/ivs/anaconda3/envs/ABD/lib/python3.7/site-packages/fire/core.py", line 681, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "bin/train_sentiment.py", line 55, in train
    train_dataset, dev_dataset, test_dataset = load_datasets(**load_extra_args)
  File "/home/ivs/anaconda3/envs/ABD/lib/python3.7/site-packages/pysentimiento/tass/datasets.py", line 76, in load_datasets
    test_df = pd.concat(test_dfs.values())
  File "/home/ivs/anaconda3/envs/ABD/lib/python3.7/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/home/ivs/anaconda3/envs/ABD/lib/python3.7/site-packages/pandas/core/reshape/concat.py", line 304, in concat
    sort=sort,
  File "/home/ivs/anaconda3/envs/ABD/lib/python3.7/site-packages/pandas/core/reshape/concat.py", line 351, in __init__
    raise ValueError("No objects to concatenate")
ValueError: No objects to concatenate`

thanks.

**Comment by finiteautomata** [comment]
Hi @iaSalazar. 

I'm amidst a big refactor of training scripts and other stuff. Could you try using the `dev` branch? I've switched from `Pipenv` to `poetry` because it was annoyingly slow (just in case you were using it). 

Check https://github.com/pysentimiento/pysentimiento/blob/dev/TRAIN.md for instructions on how to train models. It should be something in these lines

```bash
python bin/train.py "distilbert-base-multilingual-cased" \
    --output_path models/distilbert-base-sentiment-analysis \
    --task sentiment \
    --epochs 5 \
    --lang es
```

**Comment by finiteautomata** [comment]
Well, now everything is merged into `master`. Please update, reinstall, and let me know if you still have this problem
