### ISSUE TITLE
Citation

### ISSUE THREAD

**Issue by seonake** [pysentimiento/pysentimiento#2]
Hi, could you please provide how we can cite your work?
Many thanks

**Comment by finiteautomata** [comment]
Hi! Thanks for reaching out. We were planning to write a brief report of our work, but we've never done so. We were thinking of doing if after uploading some extra models.

Are you planning to publish something soon? In that case, we can write something

**Comment by seonake** [comment]
Hola, sÍ... He utilizado vuestra librería en mi TFM. Lo publicaré en
septiembre. Te envío una copia cuando lo tenga listo!

**Comment by finiteautomata** [comment]
Hello back. You can cite now this short paper https://arxiv.org/abs/2106.09462
```
@misc{perez2021pysentimiento,
      title={pysentimiento: A Python Toolkit for Sentiment Analysis and SocialNLP tasks}, 
      author={Juan Manuel Pérez and Juan Carlos Giudici and Franco Luque},
      year={2021},
      eprint={2106.09462},
      archivePrefix={arXiv},
      primaryClass={cs.CL}
}
```

**Comment by seonake** [comment]
Hi, i Will do that... For sure.
Many thanks
