### ISSUE TITLE
No support for English hate speech task?

### ISSUE THREAD

**Issue by liushhAlex** [pysentimiento/pysentimiento#20]
Hi,

Thank you for your job, I am wondering if we still cannot do the hate speech analysis in English. The ReadME shows that English is supported, but the code shows it doesn't work.

I appreciate you reply. Thanks!

**Comment by finiteautomata** [comment]
Hi @liushhAlex. Please check new version `0.3.2`, this should have been fixed. Also, be aware that hate speech algorithms are based on multi-classification models: they return 3 different variables (hateful? targeted? aggressive?) instead of just one.

Let me know if you have any other issue.
