### ISSUE TITLE
[BUG] ModuleNotFoundError: No module named 'pysentimiento'

### ISSUE THREAD

**Issue by tarishi02** [pysentimiento/pysentimiento#22]
**Describe the bug**
ModuleNotFoundError: No module named 'pysentimiento'

I have installed both from source and wheel 
!pip install git+https://github.com/pysentimiento/pysentimiento -U
!pip install pysentimiento -U

**To Reproduce**
Happening in Windows desktop works fine in colab

**Comment by finiteautomata** [comment]
Hi @tarishi02, it seems that your problem is more related to your Windows environment than to this package. Please check with `pip freeze` if `pysentimiento` is listed among your installed packages.
