### ISSUE TITLE
[Feature Proposal] Use hashformers for hashtag segmentation

### ISSUE THREAD

**Issue by ruanchaves** [pysentimiento/pysentimiento#23]
`preprocess_tweet` currently uses a very simple camel case regex to handle hashtag preprocessing. This will obviously fail for most hashtags. 

I propose to integrate [hashformers](https://github.com/ruanchaves/hashformers) with pysentimiento. Here are a few reasons to do this:

- [Hashformers](https://github.com/ruanchaves/hashformers) has been proven by two research groups to be the current state-of-the-art for hashtag segmentation. 
- It can instantly work with Spanish, English or any other language. 
- It does not add any significant extra dependencies to the library. 
- It is very easy to integrate. 

If this seems like a good idea to the maintainers of this repository ( @finiteautomata ), I can draft an initial PR for this feature.

**Comment by finiteautomata** [comment]
That would be super cool @ruanchaves! I'm a bit busy nowadays, but if you can start working on it I will be able to aid you. I think that we should do the following:

- Replace current segmentation method with `hashformers` in [`pysentimiento/preprocessing.py`](https://github.com/pysentimiento/pysentimiento/blob/master/pysentimiento/preprocessing.py#L203)
- Add some [extra tests](https://github.com/pysentimiento/pysentimiento/blob/master/tests/unit/preprocessing_test.py) 
- Compare performance in downstream tasks 

I think I can help you with the last point, which I think is not quite documented

**Comment by ruanchaves** [comment]
Nice! I will start working on the first two points and then submit a PR.

**Comment by finiteautomata** [comment]
Just writing down to remember it when you are done. We should compare time performance between the two methods too.

**Comment by finiteautomata** [comment]
Hey @ruanchaves. Any update about this? I was thinking of releasing a new version of the library next week along with other features, and if we could add this it would be great.

Let me know if you need help

**Comment by ruanchaves** [comment]
Hi @finiteautomata . I was fixing some internal time performance issues in the library, but now I'm ready to start the integration. However I believe I won't be able to deliver it in time for the next release.    

Here's the roadmap that I have in mind:

[ ] Create a **segmenter.py** that mimics the structure of **analyzer.py**, with classes like `Segmenter`, `SegmenterOutput`, and a `create_segmenter` function. There will be two language options ( English or Spanish ) and a few model options ( including Transformers, unigram models and the camel case baseline ). 

[ ] Let the `preprocess_tweet` function in **preprocessing.py** take a segmenter object ( generated by `create_segmenter` ) as one of its parameters.   

[ ] Write tests.    

[ ] Document how to use the segmenter on the README. 

I believe you can help me with the tests and documentation after I'm done with the first two steps. 

I plan to at least open a draft PR in the next few days.

**Comment by finiteautomata** [comment]
Great! No problem if you open a draft PR -- that will give me a hint on how to complete it if possible.
