### ISSUE TITLE
Package dependency torch version 1.9.0+

### ISSUE THREAD

**Issue by anthony2261** [pysentimiento/pysentimiento#24]
Not really an issue, but we use the LTS version of torch, which is currently `1.8.2`, but `pysentimiento` requires newer versions of torch. Is this solvable from your end perhaps? We just use pip's `--use-deprecated=legacy-resolver` to get around this but we were curious to see if staying on torch 1.8.2 will cause some issues for this library.

Pretty neat package btw, thanks a lot for maintaining it ❤️

**Comment by finiteautomata** [comment]
@anthony2261 Thanks for letting me know that there were LTS versions of `torch`, I wasn't really aware of such distinction!

TBH, I'm not quite sure why we need `1.9.0` version. I will try to downgrade it and check if it still works. Perhaps it was added by accident when I migrated from `pipenv` to `poetry`. I leave this open for further updates on it

**Comment by finiteautomata** [comment]
Well, LTS support was deprecated, so we shouldn't care about this anymore

https://pytorch.org/blog/pytorch-enterprise-support-update/
