### ISSUE TITLE
[BUG] error message when using preprocess_tweet

### ISSUE THREAD

**Issue by ChiaraBi** [pysentimiento/pysentimiento#28]
When using `preprocess_tweet` I got the following error message:
<img width="1266" alt="Screenshot 2022-06-28 at 18 26 06" src="https://user-images.githubusercontent.com/10097737/176231875-c016ed55-d6af-44e2-af53-ea0a0d34fde3.png">

**To Reproduce**
Run the following code on Colab:
```python
! pip install pysentimiento

from pysentimiento.preprocessing import preprocess_tweet

sample_txt = 'Hi @chiara, how are you?'
preprocessed_tweet = preprocess_tweet(sample_txt, lang="en")

```

**Environment**
- Python 3.7.13
- pysentimiento==0.3.2
- emoji==0.6.0

**Comment by finiteautomata** [comment]
Hi @ChiaraBi, I'm not able to reproduce this error. Would you mind creating a colab notebook for it?

**Comment by ChiaraBi** [comment]
Hi @finiteautomata, after re-running again the notebook it's now working also for me. Thanks!
