### ISSUE TITLE
Input Dataset

### ISSUE THREAD

**Issue by Anuraag022** [pysentimiento/pysentimiento#29]
Hi ! Thank you for sharing the wonderful piece of code for everyone to understand and use.

Was wondering if I can use your code to predict emotion for a dataset with ~ 40,000 comments and if yes, how do I got about it?

Thanks !

**Comment by finiteautomata** [comment]
Hi @Anuraag022, thanks for your kind comments.

Yes -- you can do it using the analyzer for the emotion task. Could you ellaborate a bit more about your dataset?
