### ISSUE TITLE
Download and use model locally

### ISSUE THREAD

**Issue by arieltoledo** [pysentimiento/pysentimiento#32]
Hi, guys. 
First of all, great lib, works great and it's helping me a tons in a recent project.
I'm building an app for my job, but I have some security limitations, and one of them is that I can't reach external endpoints from the internal network, so I wonder if theres any way I can load the model locally after download it.
With hugginface library it'll be something like:

`!git clone https://huggingface.co/ORGANIZATION_OR_USER/MODEL_NAME
`
```
from transformers import AutoModel

model = AutoModel.from_pretrained('./MODEL_NAME')`
```
Thanks in advance.

**Comment by finiteautomata** [comment]
Hey @arieltoledo, nice to know you enjoy this library :-)

Hmmm, checking the source code, I noticed that a bug was introduced which does not allow you to use the `model_name` parameter of the `create_analyzer` function.

```python
from pysentimiento import create_analyzer
analyzer = create_analyzer(task="sentiment", lang="es", model_name="./MODEL_NAME")
```

I'll try to fix this as soon as possible.

**Comment by arieltoledo** [comment]
@finiteautomata Great! Thanks for the quick repley.  Looking foward to it.

**Comment by finiteautomata** [comment]
@arieltoledo Acabo de liberar la versión `0.4.1` que corrige este bug. Incluyo un ejemplo de uso en [esta notebook](https://colab.research.google.com/drive/1zReSgOsdWmpvWvI_mzLRPvgJF_61YBP8#scrollTo=tHuMdSh1P0YI)

```python
from pysentimiento import create_analyzer

analyzer = create_analyzer(model_name="./bertweet-base-sentiment-analysis/", lang="en")
analyzer.predict("This is a test")
```

Avisame si tenés algún problema con esto!

**Comment by arieltoledo** [comment]
@finiteautomata probado y funciona de 10. Gracias !!
