### ISSUE TITLE
Windows aux.py issue

### ISSUE THREAD

**Issue by lucijakrusic** [pysentimiento/pysentimiento#33]
Hi! First of all, thank you for the great work!

I'm trying to use pysentimiento for my project and colab works fine, but I'm unable to install it on my Windows machine because of a file named aux.py which is a reserved filename in Windows.
The error I get:

ERROR: For req: pysentimiento==0.4.0. The wheel '..\\pysentimiento-0.4.0-py3-none-any.whl' has a file '..\\Anaconda3\\Lib\\site-packages\\pysentimiento\\aux.py' trying to install outside the target directory

**Comment by finiteautomata** [comment]
Hi @lucijakrusic, thanks for your kind comments :smile:. I'll fix this issue soon, I wasn't aware of it because I only tested it on Linux. 

I leave this open until I do it.

**Comment by finiteautomata** [comment]
I've just released version `0.4.2`. Please @lucijakrusic check it works in Windows if possible.

**Comment by lucijakrusic** [comment]
it works, thank you so much for the fast reply :)
