### ISSUE TITLE
Support for python 3.10

### ISSUE THREAD

**Issue by HugoJBello** [pysentimiento/pysentimiento#35]
Hi, first of all great work!

I am trying to install the dependency with pip in python3.10 

when I run the command:

`pip3 install git+https://github.com/pysentimiento/pysentimiento.git`

I get the error:

`ERROR: Package 'pysentimiento' requires a different Python: 3.10.4 not in '<3.10,>=3.7'`

Have you thought in making the library compatible with python3.10?

Thanks in advance.

**Comment by finiteautomata** [comment]
Hi @HugoJBello, thanks for your kind comment :smile: 

This is related to #34. TBH, it is just a matter of changing the `pyproject.toml` file to allow the 3.10 version and check if the tests are running. I am a bit out of time right now, but if you can and want, you can try it and create a PR!

**Comment by HugoJBello** [comment]
@finiteautomata I did as you suggested, I created a PR.

**Comment by finiteautomata** [comment]
Hugo:

Sorry for the delay. This week I'm out of office, but I'll merge it as soon
as I get back to work.

Thanks!

**Comment by celisa** [comment]
Any updates on this issue?

**Comment by finiteautomata** [comment]
@celisa we've been trying to keep compatibility from python 3.7 to 3.10 in #36; however, I couldn't find any feasible way to do this.

I think that I will release `pysentimiento 0.5.1` dropping dependency with 3.7, and keep maintaining `0.4.x` for the next couple of months (until `3.7` definitely gets deprecated)

**Comment by finiteautomata** [comment]
@HugoJBello and @celisa: you can now try `pysentimiento 0.5.2` which is 3.10-compatible. 

Feel free to reopen if you find any issue. Thanks @HugoJBello for your help!

**Comment by HugoJBello** [comment]
great work @finiteautomata !!
