### ISSUE TITLE
Best practices for running inference on a large dataset (spanning a few hundred million sentences)

### ISSUE THREAD

**Issue by vinayprabhu** [pysentimiento/pysentimiento#39]
Hi there!
To begin with, thank you for open-sourcing these models. 

I am trying to run pysentimiento, specifically `analyzer = create_analyzer(task="hate_speech", lang="en")` on a dataset with a few hundred million sentences.

On a Colab Pro+ instance (with Premium GPU-class and High-RAM ), I am averaging ~ 21 minutes per million inferences and the code looks like:

```python
# The file-locations are contained in parquet_list 
proba_mat_all=np.zeros((len(parquet_list),3))
N_samples=int(1e6) # Number of samples chosen to randomly sample

for ind_i,file_i in enumerate(parquet_list):
# 0: Read the parquet file
  df_i = pd.read_parquet(file_i)
  # 1: Generate random indices
  ind_random_i=np.random.choice(df_i.shape[0],N_samples,replace=False)
  # 2: Extract the text-description from these randomly sampled indices
  texts_np_i = df_i.iloc[ind_random_i].TEXT.astype(str).values[0:N_samples]
  t.tic()
  # 3: Analyze the content
  results_i=analyzer.predict(texts_np_i)
  t.toc()
  # 4: Analyze the results
  res_mat_i=np.array(list(itertools.chain.from_iterable(x.probas.values() for x in results_i))).reshape(N_samples,3)
  prob_mat_i=np.mean(res_mat_i>0.5,axis=0)*100
  proba_mat_all[ind_i,:]=prob_mat_i
  print(prob_mat_i)
  # 5: Save the intermediate assets for further analysis
  np.save(f'./hate_detect/ind_random_{ind_i}',ind_random_i)
  np.save(f'./hate_detect/res_mat_{ind_i}',res_mat_i)
  np.save(f'./hate_detect/prob_mat_{ind_i}',prob_mat_i)

```
This takes ~ 1266.57328 seconds
Given that we only need the 3x1 np.array (capturing P_hateful, P_targeted, P_aggressive) in response to a textual input (and not  the entire output-object), can you recommend some best practices from your perspective to speed things up such as ways to  increase `batch_size` etc?

Best regards

**Comment by finiteautomata** [comment]
Hey Vinay, thanks for your interest in pysentimiento 🤗

Regarding your question, all the code for prediction is in [these lines](https://github.com/pysentimiento/pysentimiento/blob/master/pysentimiento/analyzer.py#L198). Perhaps it is not quite optimized, and now I see that the batch size is not used at all.

Perhaps you can grab this function, make your own optimized version of it, and check how it is doing. I suppose the first two things I would try to adjust would be the batch size, and also try to sort the elements according to their length (so tensors for batches are as small as possible).

If you can, try these, and let me know what happens (you can use the %%timeit magic in a notebook to have some performance figures).

**Comment by ningein** [comment]
hi @vinayprabhu i'm interest in know if you optimize the performance
can you share what you did?
tanks
