### ISSUE TITLE
How to get the data

### ISSUE THREAD

**Issue by ningein** [pysentimiento/pysentimiento#41]
I run train but dont have the data. How can get it?
Tks

**Comment by finiteautomata** [comment]
@ningein: which of the tasks are you interested in?

Most Spanish datasets come from the [TASS Workshop](http://tass.sepln.org/). Some of the English datasets come from SemEval.

**Comment by ningein** [comment]
spanish sentiment
when train not founds tass.csv.
inside readme.md you write:
"1. Get the data and put it under data/
Open an issue or email us if you are not able to get the it."

I cant get it. Please help :)

**Comment by finiteautomata** [comment]
Please write to my email so I can send you the files.
