### ISSUE TITLE
[BUG] Logging Output 

### ISSUE THREAD

**Issue by jnehring** [pysentimiento/pysentimiento#42]
**Describe the bug**

The library is very verbose. It is very hard to use from Jupyter Notebook because it prints a lot of stuff which I do not need. How can I switch that off? Thank you very much

**To Reproduce**

```
from pysentimiento import create_analyzer
create_analyzer(task="sentiment", lang="en")
```

![image](https://user-images.githubusercontent.com/10537540/210341950-1977d533-bfa4-446b-8593-b285fd6a3e35.png)

**Comment by finiteautomata** [comment]
This is due to the `transformers` package logging it. Check [this page](https://huggingface.co/docs/transformers/main_classes/logging) to set a less verbose output for this library.
