### ISSUE TITLE
output embedding

### ISSUE THREAD

**Issue by taalua** [pysentimiento/pysentimiento#46]
Thank you for this work.
How to output embedding for emotion task before the classification layer? (i.e., beto-emotion-analysis)

**Comment by finiteautomata** [comment]
Hi @taalua! 

The analyzer is not saving the output embeddings anywhere, so you have to do this manually. Use `AutoModel` like this:

```python
import torch 
from transformers import AutoModel, AutoTokenizer
from pysentimiento.preprocessing import preprocess_tweet

model = AutoModel.from_pretrained("pysentimiento/robertuito-emotion-analysis")
tokenizer = AutoTokenizer.from_pretrained("pysentimiento/robertuito-emotion-analysis")


text = "I'm completely pissed off by this 😠"
preprocessed_text = preprocess_tweet(text, lang="en")

input = tokenizer(preprocessed_text)
input = {k:torch.LongTensor(v).view(1, -1) for k, v in input.items()}
model(**input) # This gets the `last_hidden_state`
```

Check [this notebook](https://colab.research.google.com/drive/1VKLV_1bUQxQrndyGhggjcd18d9fs70CW#scrollTo=1ewPDmMrDa3T) I've just created

**Comment by taalua** [comment]
Quick question, for output=model(**input), what's the difference between output[0] and output[1] ?

Thank you so much.

> Hi @taalua!
> 
> The analyzer is not saving the output embeddings anywhere, so you have to do this manually. Use `AutoModel` like this:
> 
> ```python
> import torch 
> from transformers import AutoModel, AutoTokenizer
> from pysentimiento.preprocessing import preprocess_tweet
> 
> model = AutoModel.from_pretrained("pysentimiento/robertuito-emotion-analysis")
> tokenizer = AutoTokenizer.from_pretrained("pysentimiento/robertuito-emotion-analysis")
> 
> 
> text = "I'm completely pissed off by this 😠"
> preprocessed_text = preprocess_tweet(text, lang="en")
> 
> input = tokenizer(preprocessed_text)
> input = {k:torch.LongTensor(v).view(1, -1) for k, v in input.items()}
> model(**input) # This gets the `last_hidden_state`
> ```
> 
> Check [this notebook](https://colab.research.google.com/drive/1VKLV_1bUQxQrndyGhggjcd18d9fs70CW#scrollTo=1ewPDmMrDa3T) I've just created

**Comment by finiteautomata** [comment]
The output of that last line is a [BaseModelOutputWithPoolingAndCrossAttentions](https://huggingface.co/docs/transformers/main_classes/output). This comprises:

a. An embedding representing "the whole sentence" (usually, the representation of the `[CLS]` token). This is called the `pooler_output`
b. The embeddings for each of the tokens of the sentence at their last layer (`last_hidden_state`)

Check the docs for further info.
