### ISSUE TITLE
[BUG] cannot import name 'create_analyzer'

### ISSUE THREAD

**Issue by jdfoxito** [pysentimiento/pysentimiento#47]
Error in any test

    from pysentimiento import create_analyzer
ImportError: cannot import name 'create_analyzer' from 'pysentimiento'
from pysentimiento import SentimentAnalyzer

analyzer = SentimentAnalyzer(lang="es")

# ETC ETC
```


produces


    from pysentimiento import create_analyzer
ImportError: cannot import name 'create_analyzer' from 'pysentimiento'

**Comment by finiteautomata** [comment]
Hi. Please follow the template to have support. I don't have information about your environment.

I think that code is outdated, by the way. We don't use `SentimentAnalyzer` class anymore.

**Comment by finiteautomata** [comment]
When we ask for the environment, we ask for `python` version as well as the output of `pip freeze` as stated in the template, which you missed. 

This said, I suppose your error comes from an old version of the library, as `python 3.12` is not supported yet. Try using `python 3.10`.
