### ISSUE TITLE
ImportError: cannot import name 'SentimentAnalyzer'

### ISSUE THREAD

**Issue by davesnake01** [pysentimiento/pysentimiento#5]
Hi, 

Estoy intentando ocupar el código en python3 pero me insiste que necesito esa libreria, donde se encuenta? 

ImportError: cannot import name 'SentimentAnalyzer'

Saludos,

**Comment by davesnake01** [comment]
Olvidé mencionar que esto ocurre en la primera linea del ejemplo 

from pysentimiento import SentimentAnalyzer
analyzer = SentimentAnalyzer(lang="es")

**Comment by finiteautomata** [comment]
@davesnake01 puedes dar más detalles del entorno en el que lo estás corriendo?

En el ejemplo de colab está andando perfectamente:

https://colab.research.google.com/github/finiteautomata/pysentimiento/blob/master/notebooks/PySentimiento_Sentiment_Analysis_in_Spanish.ipynb

**Comment by davesnake01** [comment]
gracias por responder, el error estaba que estaba usando otra version , actualicé a la última y funciona sin problemas

Buenisimo desarrollo , felicitaciones.

**Comment by finiteautomata** [comment]
Muchas gracias! Cualquier duda que tengas abrí un issue o contactame por mail 🤗

**Comment by JoseFernandoGV** [comment]
Hola presento problemas con el paquete; 
![Captura](https://user-images.githubusercontent.com/101729179/177773212-08f48d2e-7c3a-4275-8042-b26ecb6393b2.PNG),
No me deja utilizar la función: create_analyzer

Inglés:71 / 5.000
Resultados de traducción
Hello, I have problems with the package; It won't let me use the function: create_analyzer

**Comment by finiteautomata** [comment]
Hola @JoseFernandoGV, es difícil saber qué problema tenés así. Probaste usarlo en colab?

**Comment by Yescr** [comment]
Hola, tengo el mismo problema que comentó davesnake01. Estoy trabajando en colab y trato de importar SentimentAnalyzer de pysentimiento pero me aparece que no es posible, me podrías ayudar? 

```
!pip install --upgrade pysentimiento
#descargamos el diccionario en español 
from pysentimiento import SentimentAnalyzer
analyzer = SentimentAnalyzer(lang="es")
```

![image](https://github.com/pysentimiento/pysentimiento/assets/163377999/d2f1a02c-24cd-4a87-bb77-d2f19772f68a)

**Comment by finiteautomata** [comment]
@Yescr estás usando la API vieja. Mirá el ejemplo de [la notebook del README](https://colab.research.google.com/github/pysentimiento/pysentimiento/blob/master/notebooks/examples/pysentimiento_sentiment_analysis_in_spanish.ipynb)

**Comment by Yescr** [comment]
Muchas gracias!
