### ISSUE TITLE
Problems with Spanish hate speech

### ISSUE THREAD

**Issue by aBerridi** [pysentimiento/pysentimiento#52]
I'm currently experimenting with the hate speech detection tool in Spanish, and the results are quite catastrophic. It seems to misclassify certain statements as hate speech, misjudging their aggressiveness, while inconsistently performing well on other instances. Let me provide you with a few examples:

hate_speech_analyzer.predict("Te voy a matar, negro de mierda")
>AnalyzerOutput(output=[], probas={hateful: 0.109, targeted: 0.105, aggressive: 0.149})

hate_speech_analyzer.predict("Vuelve a tu país, negro")
>AnalyzerOutput(output=['hateful', 'aggressive'], probas={hateful: 0.806, targeted: 0.194, aggressive: 0.582})

hate_speech_analyzer.predict("podemita")
>AnalyzerOutput(output=['hateful', 'targeted', 'aggressive'], probas={hateful: 0.963, targeted: 0.927, aggressive: 0.937})

hate_speech_analyzer.predict("facha")
>AnalyzerOutput(output=[], probas={hateful: 0.093, targeted: 0.066, aggressive: 0.054})

hate_speech_analyzer.predict("gilipollas")
>AnalyzerOutput(output=[], probas={hateful: 0.076, targeted: 0.047, aggressive: 0.056})

hate_speech_analyzer.predict("babaca")
>AnalyzerOutput(output=['hateful', 'targeted', 'aggressive'], probas={hateful: 0.984, targeted: 0.974, aggressive: 0.963})

So, threats are not considered aggressive or hateful, left-wing nicknames are labeled as hateful while far-right ones are not, and the same insult in Spanish and Portuguese raises no flags in Spanish but triggers alerts in Portuguese... I can't help but feel that there is some bias in this and/or the model is not adequately trained.

**Comment by finiteautomata** [comment]
Hi! Sorry to disappoint you, but that's a problem both of the datasets...and also from the classification algorithms. Aggressiveness seem not to be very well defined in `hatEval`, the dataset used to train the model. Moreover, deep learning models tend to learn spurious correlations that "fit" the data. 

Of course the models are biased, and of course they work far from perfect. And, for the time being, I think there is little we can do about it (at least, using these kind of "lightweight" models). 

In case you are working in Spanish, you can try [this other model](https://colab.research.google.com/drive/1nktGLswbVeEas2_xCU0S_BhmH8tPBJ02#scrollTo=Z5DeW-UrcI_E). It was trained on a dataset of Twitter comments to news from media outlets. Take care that labels are not the same as in `hatEval`.
