### ISSUE TITLE
Pysentimiento in R

### ISSUE THREAD

**Issue by CCristancho** [pysentimiento/pysentimiento#53]
Congrats for putting together this library which is unique for tweets in spanish from Latinamerica.
I've been trying to make it work in R using packages text and reticulate. Using text I call the huggingface model and use their textClassify function but I get scores for POS, NEU and NEG classes with values beetween 0 and 4... I haven't been able to import your create_analyzer function and I guess this is why I don't get the expected probability values. Thanks for any advice.

**Comment by finiteautomata** [comment]
Hi! Thanks 🤗

I suggest you try to run `pysentimiento` in python. Running on reticulate and other middlewares between R and python might incur in undefined behaviours as the one you are experiencing, which are extremely difficult to debug and also to fix.

**Comment by finiteautomata** [comment]
Closing this. Feel free to contact me again.
