### ISSUE TITLE
ValueError: libcublas.so.*[0-9] not found in the system path [BUG] 

### ISSUE THREAD

**Issue by pelaezluis** [pysentimiento/pysentimiento#55]
**Describe the bug**
When I run the code in my windows pc, it's ok, but when I try to create a docker image, it fails

**To Reproduce**
from pysentimiento import create_analyzer
from json import dumps

def analyze_text(text: str):
    emotion_analyzer = create_analyzer(task="emotion", lang="en")
    sentiment_analyzer = create_analyzer(task="sentiment", lang="en")
    hate_analyzer = create_analyzer(task="hate_speech", lang="en")
    emotion = emotion_analyzer.predict(text).output
    sentiment = sentiment_analyzer.predict(text).output
    intention = hate_analyzer.predict(text).output  # can be empty
    sentiments = {"emotion": emotion, "sentiment": sentiment, "intention": intention}
    sentiments = dumps(sentiments)
    return sentiments

**Expected behavior**
Show the sentiments and emotions

**Environment**
[tool.poetry.dependencies]
python = "^3.10"
fastapi = "^0.97.0"
pysentimiento = "^0.7.1"
httpx = "^0.24.1"
redis = "^4.5.5"
accelerate = "^0.20.3"
sqlmodel = "^0.0.8"
uvicorn = "^0.22.0"
fastapi-pagination = "^0.12.4"
python-dotenv = "^1.0.0"

[tool.poetry.group.dev.dependencies]
black = "^23.3.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

**Additional context**
Here the entire error
ValueError: libcublas.so.*[0-9] not found in the system path ['/code', '/usr/local/bin', '/code', '/usr/local/lib/python310.zip', '/usr/local/lib/python3.10', '/usr/local/lib/python3.10/lib-dynload', '/root/.local/lib/python3.10/site-packages', '/usr/local/lib/python3.10/site-packages']

**Comment by finiteautomata** [comment]
Hi Luis. It seems this is a problem more related to your environment rather to `pysentimiento`, isn't it?

**Comment by pelaezluis** [comment]
Well, I installed the version 6 and it works, it is related with the use of gpu
