### ISSUE TITLE
below Issue when we use transformer code

### ISSUE THREAD

**Issue by avinashpaul** [pysentimiento/pysentimiento#6]
---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
<ipython-input-2-13a82d3d4536> in <module>
      1 from transformers import AutoTokenizer, AutoModelForSequenceClassification
      2 
----> 3 tokenizer = AutoTokenizer.from_pretrained("finiteautomata/beto-sentiment-analysis")
      4 
      5 model = AutoModelForSequenceClassification.from_pretrained("finiteautomata/beto-sentiment-analysis")

~/thesis/copycat/copy_env/lib64/python3.6/site-packages/transformers/models/auto/tokenization_auto.py in from_pretrained(cls, pretrained_model_name_or_path, *inputs, **kwargs)
    421             tokenizer_class_py, tokenizer_class_fast = TOKENIZER_MAPPING[type(config)]
    422             if tokenizer_class_fast and (use_fast or tokenizer_class_py is None):
--> 423                 return tokenizer_class_fast.from_pretrained(pretrained_model_name_or_path, *inputs, **kwargs)
    424             else:
    425                 if tokenizer_class_py is not None:

~/thesis/copycat/copy_env/lib64/python3.6/site-packages/transformers/tokenization_utils_base.py in from_pretrained(cls, pretrained_model_name_or_path, *init_inputs, **kwargs)
   1708 
   1709         return cls._from_pretrained(
-> 1710             resolved_vocab_files, pretrained_model_name_or_path, init_configuration, *init_inputs, **kwargs
   1711         )
   1712 

~/thesis/copycat/copy_env/lib64/python3.6/site-packages/transformers/tokenization_utils_base.py in _from_pretrained(cls, resolved_vocab_files, pretrained_model_name_or_path, init_configuration, *init_inputs, **kwargs)
   1814             for token, index in added_tok_encoder_sorted:
   1815                 assert index == len(tokenizer), (
-> 1816                     f"Non-consecutive added token '{token}' found. "
   1817                     f"Should have index {len(tokenizer)} but has index {index} in saved vocabulary."
   1818                 )

AssertionError: Non-consecutive added token '[USER]' found. Should have index 31005 but has index 31002 in saved vocabulary.

**Comment by finiteautomata** [comment]
Ouch...I've changed some of this because we added incorrectly "[USER]" tokens as special when they shouldn't be. 

Could you provide an example to reproduce the error?

**Comment by mvargas33** [comment]
Just tried to import the library and got the same error:

```
from transformers import AutoTokenizer, AutoModelForSequenceClassification
tokenizer = AutoTokenizer.from_pretrained("finiteautomata/beto-sentiment-analysis")
model = AutoModelForSequenceClassification.from_pretrained("finiteautomata/beto-sentiment-analysis")
```
transformers==4.5.1
tokenizers==0.10.2

**Comment by finiteautomata** [comment]
It seems to be a problem with that version of `transformers` – perhaps I created the models with later versions. 

Updating `transformers` seems to correct the issue

**Comment by finiteautomata** [comment]
@avinashpaul could you try updating transformers? Let me know if that does not work
