### ISSUE TITLE
[BUG] installation issue MAC OS edit: Also Windows 10...

### ISSUE THREAD

**Issue by marcobrianza** [pysentimiento/pysentimiento#61]
Hello, I could succesfully test the lib on colab but on my mac the installation fails and cannot figure out why.

since I belived that Apple Silicon might have been problematic I tested Windows 10 but also there is a setup issue

**Describe the bug**
the installation fails due a dependency error
Attaching the error log file

**To Reproduce**
pip3 install pysentimiento

**Environment**

Python 3.12.1

pip freeze
altair==5.2.0
attrs==23.1.0
blinker==1.7.0
cachetools==5.3.2
certifi==2023.11.17
charset-normalizer==3.3.2
cleantext==1.1.4
click==8.1.7
filelock==3.13.1
fsspec==2023.12.2
gitdb==4.0.11
GitPython==3.1.40
huggingface-hub==0.20.2
idna==3.6
importlib-metadata==6.11.0
Jinja2==3.1.2
joblib==1.3.2
jsonschema==4.20.0
jsonschema-specifications==2023.12.1
markdown-it-py==3.0.0
MarkupSafe==2.1.3
mdurl==0.1.2
nltk==3.8.1
numpy==1.26.2
packaging==23.2
pandas==2.1.4
Pillow==10.1.0
protobuf==4.25.1
pyarrow==14.0.2
pydeck==0.8.1b0
Pygments==2.17.2
python-dateutil==2.8.2
pytz==2023.3.post1
PyYAML==6.0.1
referencing==0.32.0
regex==2023.12.25
requests==2.31.0
rich==13.7.0
rpds-py==0.16.2
safetensors==0.4.1
six==1.16.0
smmap==5.0.1
streamlit==1.29.0
tenacity==8.2.3
textblob==0.17.1
tokenizers==0.15.0
toml==0.10.2
toolz==0.12.0
tornado==6.4
tqdm==4.66.1
transformers==4.36.2
typing_extensions==4.9.0
tzdata==2023.4
tzlocal==5.2
urllib3==2.1.0
validators==0.22.0
zipp==3.17.0

[error.txt](https://github.com/pysentimiento/pysentimiento/files/13962221/error.txt)

**Comment by finiteautomata** [comment]
It seems the issue is related to `tokenizers`. Have you tried installing this package alone?

**Comment by marcobrianza** [comment]
Hi, just tried again today and it works! it looks like someone fixed the dependencies in the meantime.
