### ISSUE TITLE
A strange result in a sentiment analysis evaluation

### ISSUE THREAD

**Issue by pr3ssh** [pysentimiento/pysentimiento#63]
Hi all.
First of all, thanks for your work.
I was testing your sentiment analysis model with pysentimiento and also with transformers' pipelines and I found a strange result in a sentiment analysis evaluation for the Spanish expression "Te odio". The result is:

`{'label': 'NEU', 'score': 0.925968587398529}`

Is that result correct or maybe I'm doing something wrong using your model/package?
Thxx.

**Comment by finiteautomata** [comment]
Hey @pr3ssh, thanks!

Sorry to hear about this error but... well, that's something that can happen.

However, I tested "Te odio" using our analyzer and it gives me different results
```python
from pysentimiento import create_analyzer

analyzer = create_analyzer(task="sentiment", lang="es")

analyzer.predict("Te odio")
# Returns AnalyzerOutput(output=NEG, probas={NEG: 0.656, NEU: 0.289, POS: 0.055})
```

See [this notebook](https://colab.research.google.com/drive/1Jt-mo-lhSORhPnrU6vqtVhXc9eqyJJHi?usp=sharing). Have you done something different?

**Comment by pr3ssh** [comment]
You are right @finiteautomata , thanks!
Do you know why the result is totally different if I use your model with a transformers' pipeline?
In that case my code is:

```
from transformers import pipeline

sentiment_pipeline = pipeline(
    task="sentiment-analysis",
    model="finiteautomata/bertweet-base-sentiment-analysis")

data = ["Te quiero", "Te odio"]

sentiment_pipeline(data)
```

**Comment by finiteautomata** [comment]
The issue is that you are using `finiteautomata/bertweet-base-sentiment-analysis` which is trained in English, not in Spanish 🙃 you should use [this](https://huggingface.co/pysentimiento/robertuito-sentiment-analysis) model instead!

**Comment by finiteautomata** [comment]
BTW... `te quiero` is giving `NEU` with this other model 🤷 

I guess this might be due to the fact that our model is only trained on tweets, and it is not that common to see this kind of interactions.

**Comment by pr3ssh** [comment]
Thank you so much for your support @finiteautomata
