### ISSUE TITLE
Why epochs is 5?

### ISSUE THREAD

**Issue by gongshaojie12** [pysentimiento/pysentimiento#7]
Hi,I noticed that the `epochs` is 5 during training, why not set it a bit larger? Is it because the `epochs` are set too large to cause overfitting? Thanks!

**Comment by finiteautomata** [comment]
@gongshaojie12 I just used a fairly standard number of epochs. BTW, I observed no increased performance by running them for a larger period of time. 

BTW, you can try it to train them for a longer period of time and let me know if that yields better results. Let me know if you want to do so

**Comment by gongshaojie12** [comment]
Hi @finiteautomata I set epochs to 30, `eval_loss` and `train_loss` are as follows: 

![图片](https://user-images.githubusercontent.com/6407116/127771852-38b36bcb-eae5-4fb7-9736-7e461eed6921.png)

As can be seen from the figure, from the third epoch, `eval_loss` starts to rise, while `train_loss` keeps falling. It shows that the model has been overfitting. What is the reason? I guess the reasons may be: 1, the data set is too small, 2, the pre-training model for fine-tuning is too large.

**Comment by finiteautomata** [comment]
@gongshaojie12 great, thanks for your experiments. I understand that you observed no performance increase by setting a larger number of epochs; moreover, it seems that ~5 epochs seems to be ok. 

What dataset are you using? SemEval (English) or TASS(Spanish)?

**Comment by gongshaojie12** [comment]
Hi @finiteautomata The dataset I used is `EmoEvent(dataset_emotions_EN.csv)`. The training command is: `python bin/train_emotion.py "roberta-base" models/roberta-base-emotion-analysis/ --epochs 5 --lang en` . Is the data set used incorrectly?

**Comment by finiteautomata** [comment]
@gongshaojie12 that is the dataset used for English Emotion Analysis. As you can see, that dataset is small-sized – the same occurs with the Spanish version of EmoEvent, and the Sentiment Analysis in Spanish (TASS). We used 10 epochs for Sentiment Analysis in English as that dataset is bigger (around 50k instances)

**Comment by gongshaojie12** [comment]
Hi @finiteautomata Thanks for your reply. What if I want to get more EmoEvent data?

**Comment by finiteautomata** [comment]
@gongshaojie12 if you want to get more data, you should collect and annotate your own corpus. You can get more information on how the authors did so here https://github.com/fmplaza/EmoEvent-multilingual-corpus

**Comment by gongshaojie12** [comment]
OK,Thanks a lot

**Comment by finiteautomata** [comment]
Closing this. Feel free to reopen or send email if you have any doubt
