### ISSUE TITLE
Tokenizer Error

### ISSUE THREAD

**Issue by JOTOR** [pysentimiento/pysentimiento#8]
Hello, 
I am getting an error when the following code (extracted from the examples) is executed:

```
from pysentimiento import SentimentAnalyzer
analyzer = SentimentAnalyzer(lang="es")

```
Error:

`AssertionError: Non-consecutive added token '@usuario' found. Should have index 31006 but has index 31002 in saved vocabulary.`

Thank you

**Comment by finiteautomata** [comment]
Hi. Can you give information about environment, `pysentimiento` and `transformers` version, etc?

**Comment by JOTOR** [comment]
Hello, 

Python = 3.8.11
transformers = 4.3.3
pysentimiento = 0.2.5

Thank you

**Comment by finiteautomata** [comment]
Yes, I'm sorry – I must update `setup.py` so that it uses `transformers>=4.6.1`. For the time being, please run `pip install -U transformers` and make sure you get  a proper version

**Comment by JOTOR** [comment]
Hello

Upgrading the transformers library to 4.9.2 resolved the issue.

Thank you so much for your help
